# Generated by Django 5.1.7 on 2025-03-25 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
            ],
        ),
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="pulication_image/post/%y/%m/%d", verbose_name="Foto"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Titulo")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Esta Publicado?"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Criado"),
                ),
                ("cost", models.TextField(verbose_name="Custos")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("recommendations", models.TextField(verbose_name="Recomendações")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.categorymodel",
                        verbose_name="Categoria",
                    ),
                ),
            ],
        ),
    ]
