# Generated by Django 5.1.7 on 2025-04-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postmodel",
            old_name="recommendations",
            new_name="recomendations",
        ),
    ]
