# Generated by Django 5.1.7 on 2025-04-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="message",
            field=models.TextField(verbose_name="Mensagem"),
        ),
    ]
