# Generated by Django 5.1.7 on 2025-04-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
    ]
